language: php

branches:
  # Only test the master branch
  only:
    - master

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi
  - composer install -n --prefer-source

script:
 - ./vendor/bin/codecept run
